language: php
dist: trusty

matrix:
  include:
    - php: 5.6
      env: deps=low
    - php: hhvm
      env: deps=low
    - php: 7.0
      env: deps=low
    - php: 5.6
    - php: hhvm
    - php: 7.0
    - php: 7.1
    - php: 7.2
  fast_finish: true

before_install:
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer self-update
  - if [ "$deps" = "no" ]; then composer --prefer-stable --no-interaction update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable --no-interaction update; fi;

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict
    - deps=no

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpcpd src/
  - ./vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

after_success:
  - travis_retry php vendor/bin/coveralls

cache:
  directories:
    - vendor

sudo: false
