language: php
dist: trusty

matrix:
  include:
    - php: 8.0
    - php: 8.0
      env: deps=low
    - php: 8.1
  fast_finish: true

install:
  - composer self-update
  - if [ "$deps" = "no" ]; then COMPOSER_MEMORY_LIMIT=-1 composer --prefer-stable --no-interaction update; fi;
  - if [ "$deps" = "low" ]; then COMPOSER_MEMORY_LIMIT=-1 composer --prefer-lowest --prefer-stable --no-interaction update; fi;

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict
    - deps=no

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -n --standard=PSR2,PSR12 src/
  - ./vendor/bin/phpcpd src/
  - ./vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

after_success:
  - travis_retry php vendor/bin/php-coveralls

cache:
  directories:
    - vendor

sudo: false
