services:
    emoe_guzzle.monolog_formatter:
        class: 'GuzzleHttp\MessageFormatter'
        public: false
        arguments:
            - '%emoe_guzzle.log.format%'

    emoe_guzzle.monolog_log_adapter:
        class: 'Emoe\GuzzleBundle\Log\MonologLogAdapter'
        public: false
        arguments:
            - '@monolog.logger'

    emoe_guzzle.request_monolog_middleware:
        class: 'Emoe\GuzzleBundle\Middleware\RequestLoggerMiddleware'
        public: false
        arguments:
            - '@emoe_guzzle.monolog_log_adapter'
            - '@emoe_guzzle.stopwatch'
            - '@emoe_guzzle.monolog_formatter'

